name: CITEST
on:
  workflow_dispatch:
    inputs:
      subscription-id:
        description: "The azure subscription ID of the subscription to be onboarded"
        required: true
        default: "f9d926e7-345a-4419-8d6e-515cb3a95383"

jobs:

  verify:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v4
      #  with:
      #    repository: karthikbn/deploy-scripts
      #    ref: master
      #    token:  ${{ secrets.SECRET_TOKEN }}

      - name: Verify Job Status JSON Exit
        id: VerifyJson
        run: |
          if [ -f "${{ inputs.subscription-id }}.json" ]; then
            echo "Job Status Json Already Exist"
          else
            echo "Subscription Job Status JSON Dos Not exists, creating status JSON !"
            touch test.json
            pwd
            ls -lrta
            echo "{ \"${{ inputs.subscription-id }}\" : \"Job1\" }" > ${{ inputs.subscription-id }}.json
            git config --global user.email "karthikbn1410@gmail.com"
            git config --global user.name "karthikbn"
            git add .
            git commit -m "adding Status Job Json"
            git push
          fi

  Job1_validate:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: verify
    outputs:
        current_status: ${{ steps.status.outputs.current_status }}
    steps:
      - name: Check for current status
        id: status
        run: |
           current_status=`cat ${{ inputs.subscription-id }}.json | jq -r .${{ inputs.subscription-id }}`
           echo "current_status=$current_status" >> $GITHUB_OUTPUT

  Job1_execute:
    runs-on: ubuntu-latest
    needs: Job1_validate
    if: ${{ always() && needs.verify.outputs.current_status == 'Job1' }}
    steps:
      - name: Trigger Workflow and wait
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: karthikbn
          repo: deploy-scripts
          github_token: ${{ secrets.SECRET_TOKEN }}
          #github_user: github-user
          workflow_file_name: blank.yml
          ref: master
          wait_interval: 10
          client_payload: '{}'
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: true

  Job1_update:
    runs-on: ubuntu-latest
    needs: Job1_execute
    if: ${{ always() }}
    steps:
      - name: Job 1 Update
        if: ${{ always() && needs.Job1_execute.result == 'success' }}
        run: |
           tmp=$(mktemp)
           jq '.${{ inputs.subscription-id }} = "Job2"' ${{ inputs.subscription-id }}.json > "$tmp" && mv "$tmp" ${{ inputs.subscription-id }}.json
