name: CI
on:
  push:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
    continue-on-error: false

  prepare:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests package
        run: pip install requests
    continue-on-error: false

  trigger:
     needs: [build, prepare]
     runs-on: ubuntu-latest
     steps:
       - name: Trigger Other WorkFlow
         env:
          SECRET_TOKEN: ${{ secrets.NITHINTEST }}
         id: trigger1
         run: |
           python - <<EOF
           import requests
           import json
           import os

           print("Inside python")
     continue-on-error: false
