name: CI
on:
  push:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
    continue-on-error: false

  prepare:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install requests package
        run: pip install requests
    continue-on-error: false

  trigger-workflow:
     needs: [build, prepare]
     runs-on: ubuntu-latest
     steps:
       - name: Trigger Other WorkFlow
         env:
          SECRETTOKEN: ${{ secrets.SECRET_TOKEN }}
         id: trigger1
         run: |
           python - <<EOF
           import requests
           import json
           import os
           import random
           import string
           import datetime
           import requests
           import time

           print("Inside python")
           github_token = os.environ.get('SECRETTOKEN')
           #to fetch last run
           run_identifier = ''.join(random.choices(string.ascii_uppercase + string.digits, k=15))
           print(run_identifier)
           workflow_runs = ''
           # filter runs that were created after this date minus 5 minutes
           delta_time = datetime.timedelta(minutes=5)
           run_date_filter = (datetime.datetime.utcnow()-delta_time).strftime("%Y-%m-%dT%H:%M")

           url = "https://api.github.com/repos/karthikbn/deploy-scripts/actions/workflows/blank.yml/dispatches"
           headers = {
               'Accept': 'application/vnd.github+json',
               'Authorization': f'Bearer {github_token}',
               'X-GitHub-Api-Version': '2022-11-28',
               'Content-Type': 'application/json'
           }

           payload = json.dumps({
               "ref": "master",
               "inputs": {
                   "id": f"[\"{run_identifier}\"]",
                   "values": "temp"
               }
           })

           response = requests.post(url, headers=headers, data=payload)
           print(f"dispatch workflow status: {response.status_code} | workflow identifier: {run_identifier}")
           workflow_id = ""
           time.sleep(30)
           while workflow_id == "":
             r = requests.get(f"https://api.github.com/repos/karthikbn/deploy-scripts/actions/runs?created=%3E{run_date_filter}",
                 headers = headers)
             json_data = r.json()
             print(json_data)
             runs = r.json()["workflow_runs"]
             if len(runs) > 0:
               for workflow in runs:
                   jobs_url = workflow["jobs_url"]
                   print(f"get jobs_url {jobs_url}")

                   r = requests.get(jobs_url, headers= authHeader)

                   jobs = r.json()["jobs"]
                   if len(jobs) > 0:
                     # we only take the first job, edit this if you need multiple jobs
                     job = jobs[0]
                     steps = job["steps"]
                     if len(steps) >= 2:
                         second_step = steps[1] # if you have position the run_identifier step at 1st position
                         if second_step["name"] == run_identifier:
                             workflow_id = job["run_id"]
                     else:
                         print("waiting for steps to be executed...")
                         time.sleep(3)
                   else:
                       print("waiting for jobs to popup...")
                       time.sleep(3)
             else:
                 print("waiting for workflows to popup...")
                 time.sleep(3)
           print(f"workflow_id: {workflow_id}")
           EOF
     continue-on-error: false
