name: CI
on:
  push:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
    continue-on-error: false

  prepare:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install requests package
        run: pip install requests
    continue-on-error: false

  trigger:
     needs: [build, prepare]
     runs-on: ubuntu-latest
     steps:
       - name: Trigger Other WorkFlow
         env:
          SECRETTOKEN: ${{ secrets.SECRET_TOKEN }}
         id: trigger1
         run: |
           python - <<EOF
           import requests
           import json
           import os

           print("Inside python")
           github_token = os.environ.get('SECRETTOKEN')
           url = "https://api.github.com/repos/karthikbn/deploy-scripts/actions/workflows/blank.yml/dispatches"
           headers = {
               'Accept': 'application/vnd.github+json',
               'Authorization': f'Bearer {github_token}',
               'X-GitHub-Api-Version': '2022-11-28',
               'Content-Type': 'application/json'
           }

           payload = json.dumps({
               "ref": "master",
               "inputs": {
                   "values": "temp"
               }
           })

           requests.post(url, headers=headers, data=payload)
           EOF
     continue-on-error: false
